Algoritmo "Pagina41exercicioK"
// Disciplina : Lógica de Programação
// Professor  : Jailson Costa dos Santos
// Descrição  : Mostrar se é maior que 3
// Autor(a)   : Gabriel Henrique Alves Rocha 
// Data atual : 05/04/2026
Var
// Seção de Declarações das variáveis 
valor : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 Escreva("Digite o valor: ")
   Leia(valor)

   se valor <4  entao
      escreval(valor)
   senao
        escreval("O valor é maior que 3")
   fimse

Fimalgoritmo