Algoritmo "Pagina25exercicioH"
// Disciplina : Lógica de Programação
// Professor  : Jailson Costa dos Santos
// Descrição  : Volume de ciaxa retangular
// Autor(a)   : Gabriel Henrique Alves Rocha 
// Data atual : 05/04/2026
Var
// Seção de Declarações das variáveis 
  comprimento, altura, largura, volume : real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite o comprimento: ")
   leia(comprimento)

   escreva("Digite o altura: ")
   leia(altura)

   escreva("Digite o largura: ")
   leia(largura)

   volume<-comprimento*altura*largura

   escreva("Volume da caixa: ", volume)
Fimalgoritmo