Algoritmo "Pagina66exercicioF"
// Disciplina : Lógica de Programação
// Professor  : Jailson Costa dos Santos
// Descrição  : Divisíveis por 4 menor que 200
// Autor(a)   : Gabriel Henrique Alves Rocha 
// Data atual : 06/04/2026
Var
// Seção de Declarações das variáveis 
 i : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  para i de 1 ate 199 passo 1 faca
      se i mod 4 = 0 entao
         escreva(i, " ")
         i<- i+1
      senao
         i<- i+1
      fimse
   fimpara

Fimalgoritmo