Algoritmo "Pagina66exercicioJ"
// Disciplina : Lógica de Programação
// Professor  : Jailson Costa dos Santos
// Descrição  : Conversão de graus
// Autor(a)   : Gabriel Henrique Alves Rocha 
// Data atual : 06/04/2026
Var
   // Seção de Declarações das variáveis
   celcius : inteiro
   fahrenheit  : real


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   para celcius de 10 ate 100 passo 10 faca
      fahrenheit <- ((9*celcius)+160)/5
      escreval(celcius, "°C = ", fahrenheit, "°F")
   fimpara

Fimalgoritmo