Algoritmo "Pagina41exercicioI"
// Disciplina : Lógica de Programação
// Professor  : Jailson Costa dos Santos
// Descrição  : Impar ou par
// Autor(a)   : Gabriel Henrique Alves Rocha 
// Data atual : 05/04/2026
Var
   // Seção de Declarações das variáveis
   valor : inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreva("Digite o valor: ")
   Leia(valor)

   se valor mod 2 = 0  entao
      escreval("Par")
   senao
      escreval("Ímpar")
   fimse

Fimalgoritmo